name: basic_workflow

on:
  workflow_dispatch: 
  
   inputs:          
        Execution_Environment:
          description: 'Execution Environment'
          default: 'NON-PROD'
          required: true
          type: string

jobs:
  triggerAutomationTest:
  
    runs-on: btwn00XXXX
    environment: ${{ github.event.inputs.Execution_Environment }}
    
    env:
        #Token Related Info
        GH_READ_PACKAGES_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}
        LDAP_USERID: ${{ secrets.LDAP_USERID }} 
        LDAP_PASSWORD: ${{ secrets.LDAP_PASSWORD }}
        #Application Username(s) and Password(s)
        WEBAPPONE_PASSWORD: ${{ secrets.WEBAPPONE_PASSWORD }}
        WEBAPPONE_USERNAME: ${{ secrets.WEBAPPONE_USERNAME }}
        WEBAPPTWO_PASSWORD: ${{ secrets.WEBAPPTWO_PASSWORD }}
        WEBAPPTWO_USERNAME: ${{ secrets.WEBAPPTWO_USERNAME }}
        #Application Test Data
        WEBAPPONE_TD: ${{ secrets.WEBAPPONE_TD }}
        WEBAPPTWO_TD: ${{ secrets.WEBAPPTWO_TD }}        
    
    steps:
    - uses: actions/checkout@v3
      with:
          ref: gh_actions_feature
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
       maven-version: 3.8.2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
     
    - name: Run tests        
      run: mvn --settings ./settings.xml -B test package --file pom.xml
     
    - name: Attach HTML Extent Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: Automation-Report
          path: "target/extent-reports.zip"
    
  analize:
    if: always()
    name: Analize test result
    runs-on: windows-latest
    needs: [triggerAutomationTest]
     
    steps:
      - name: Download Automation-Report.html
        uses: actions/download-artifact@v3
        with:
          name: Automation-Report
